#!/bin/bash

set -eu

TEMPDIR="$(mktemp -d)"
chmod 755 "$TEMPDIR"

git archive HEAD | tar x -C "$TEMPDIR"

rsync -aq --progress \
  --delete \
  --exclude /venv \
  --exclude /install \
  --exclude /mdcs \
  --exclude /docs \
 "$TEMPDIR"/  /var/www/vhosts/mdc.hatchlane.com/httpdocs/

if [[ ! -d /var/www/vhosts/mdc.hatchlane.com/httpdocs/venv ]]; then
  python3 -m virtualenv /var/www/vhosts/mdc.hatchlane.com/httpdocs/venv
fi

set +u
. /var/www/vhosts/mdc.hatchlane.com/httpdocs/venv/bin/activate
set -u

pip install -r /var/www/vhosts/mdc.hatchlane.com/httpdocs/etc/requirements.txt
deactivate

[[ ! -d /var/www/vhosts/mdc.hatchlane.com/httpdocs/mdcs ]] && mkdir -m 777 /var/www/vhosts/mdc.hatchlane.com/httpdocs/mdcs
[[ ! -d /var/www/vhosts/mdc.hatchlane.com/httpdocs/tmp ]] && mkdir -m 777 /var/www/vhosts/mdc.hatchlane.com/httpdocs/tmp
[[ ! -L /var/www/vhosts/mdc.hatchlane.com/httpdocs/tmp/mako ]] && ln -sn ../mako /var/www/vhosts/mdc.hatchlane.com/httpdocs/tmp/mako

rm -rf "$TEMPDIR"
