#!/bin/bash

set -eu

TARGET=/var/www/vhosts/mdc.hatchlane.com/httpdocs
NEW_VENV=0

while getopts "p" arg; do
  case "$arg" in
    p)
      NEW_VENV=1
      ;;
  esac
done

shift $((OPTIND-1))


TEMPDIR="$(mktemp -d)"
chmod 755 "$TEMPDIR"

git archive HEAD | tar x -C "$TEMPDIR"

git rev-parse HEAD > "$TEMPDIR/commit"

rsync -rlDq \
  --delete \
  --exclude /apps \
  --exclude /venv \
  --exclude /install \
  --exclude /mdc_images \
  --exclude '/mdcs/*.json' \
  --include /mdcs/.htaccess \
  --exclude /docs \
 "$TEMPDIR"/  "$TARGET/"

if [[ ! -d "${TARGET}/venv" || $NEW_VENV -eq 1 ]]; then
  [[ -d "${TARGET}/venv" ]] && rm -rf "${TARGET}/venv"
  /opt/rh/rh-python38/root/usr/bin/python3.8 -m venv "${TARGET}/venv"
  "${TARGET}/venv/bin/pip" install --upgrade pip
fi

"${TARGET}/venv/bin/pip" install -r "${TARGET}/etc/requirements.txt"

WRITABLE_DIRS=("mdcs" "mdcs_html" "cache" "mdc_images")

for DIR in "${WRITABLE_DIRS[@]}"; do
  [[ ! -d "${TARGET}/${DIR}" ]] && mkdir -m 777 "${TARGET}/${DIR}";
done

rm -rf "$TEMPDIR"
